[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "python313", "python313Packages.pip"]

[phases.install]
cmds = [
  "python3 -m pip install --break-system-packages yt-dlp",
  "npm install"
]

[start]
cmd = "npm start"